Repository iml-wg/HEPML-LivingReview, pull requests merged in 2021-01, with the labels that each got.

#40 fix: Update README to match make_md.py
  README.md
Labels: fix

#41 ci: Use texlive-action GitHub Action over texlive-full Docker image
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: CI

#44 paper: Add LHC Olympics 2020 and MLPF
  HEPML.bib
  HEPML.tex
  README.md
Labels: Paper

#42 paper: Add Quantum Machine Learning in High Energy Physics
  HEPML.bib
  HEPML.tex
  README.md
Labels: Paper

#46 paper: Add OTUS ML Simulator
  HEPML.bib
  HEPML.tex
  README.md
Labels: Paper
