Repository iml-wg/HEPML-LivingReview, pull requests merged in 2022-12, with the labels that each got.

#126 paper: Add manuscript on quantum machine learning
  HEPML.bib
  HEPML.tex
  README.md
Labels: Paper

#118 paper: Add Event Classification with Multi-step Machine Learning proceedings
  HEPML.bib
  HEPML.tex
  README.md
Labels: Paper

#113 fix: Properly select } in \textbf argument
  README.md
  make_md.py
Labels: fix

#129 chore: Add journal information for "Application of Transfer Learning to Neutrino Interaction Classification"
  HEPML.bib
  HEPML.tex
  README.md
Labels: chore
