Repository iml-wg/HEPML-LivingReview, pull requests merged in 2022-05, with the labels that each got.

#103 paper: Add CNN neutrino classifier and small patch CNN track/shower classifier DUNE papers
  HEPML.bib
  HEPML.tex
  README.md
Labels: enhancement, Paper

#104 ci: Use latest CPython for tests
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: CI

#105 chore: Remove unused PyYAML and json dependencies
  make_md.py
  requirements.txt
Labels: chore
